#!/usr/bin/env python
# coding: utf-8

# # Distribution of cosine distance for minimal syntax pairs

# In[33]:


from transformers import AutoTokenizer, AutoModel
import torch
import numpy as np
import pandas as pd
import os, sys, time, re
import matplotlib.pyplot as plt
import pickle
from scipy.spatial.distance import cosine
import seaborn as sns

get_ipython().run_line_magic('matplotlib', 'inline')


# ## Load sentence pairs
# 
# "Targeted Syntactic Evaluation of Language Models" by Marvin and Linzen (2018).
# https://github.com/BeckyMarvin/LM_syneval
# 
# Or use the ones generated by CheckList.

# In[21]:


with open('../data/sents.pkl', 'rb') as f:
  data = pickle.load(f)
  data = list(data)


# In[7]:


len(data)


# In[8]:


data[:5]


# ## Load BERT

# In[25]:


model_name = 'roberta-base'
bert_tokenizer = AutoTokenizer.from_pretrained(model_name)
bert_model = AutoModel.from_pretrained(model_name)


# In[26]:


def evaluate_contextual_diff(pair):
    source, target = pair[0], pair[1]
    src_ids = torch.tensor(bert_tokenizer.encode(source)).unsqueeze(0)
    src_vec = bert_model(src_ids)[0].mean(dim=1)[0]  # (768,) torch.tensor
    
    tgt_ids = torch.tensor(bert_tokenizer.encode(target)).unsqueeze(0)
    tgt_vec = bert_model(tgt_ids)[0].mean(dim=1)[0]
    
    d_emb = len(src_vec)  # 768
    diff = src_vec - tgt_vec
    return diff # 768-dimensional torch.tensor


# ## Evaluate and plot

# In[27]:


vecs = np.stack([evaluate_contextual_diff(pair).detach().numpy() for pair in data])


# In[46]:


cosine_distances = []
for i in range(len(vecs)):
  for j in range(i+1, len(vecs)):
    cosine_distances.append(pd.Series({
      'cosdist': cosine(vecs[i,:], vecs[j,:]),
      'sent1a': data[i][0],
      'sent1b': data[i][1],
      'sent2a': data[j][0],
      'sent2b': data[j][1],
    }))


# In[47]:


cosine_distances = pd.DataFrame(cosine_distances)


# In[49]:


sns.distplot(cosine_distances.cosdist, bins=40)
plt.title(f"Cosine similarity distribution using model: {model_name}")


# In[61]:


np.mean(cosine_distances.cosdist)


# ## Inspect most similar and dissimilar pairs
# 
# Some sentences seem questionable: "The man took the dog a walk".

# In[55]:


cosine_distances.sort_values('cosdist').head(5)


# In[58]:


cosine_distances.sort_values('cosdist', ascending=False).head(5)

